### ISSUE TITLE
Fails if directory for storing csv report does not exist.

### ISSUE THREAD

**Issue by RemingtonRohel** [SuperDARNCanada/borealis-data-utils#8]
Running `borealis_gaps.py` new on sdc-serv yielded the following error:

```
Traceback (most recent call last):
  File "/home/dataman/borealis-data-utils/borealis_gaps.py", line 453, in <module>
    print_gaps(gaps_dict, first_timestamp, last_timestamp, gap_spacing, print_filename)
  File "/home/dataman/borealis-data-utils/borealis_gaps.py", line 289, in print_gaps
    with open(print_filename, "a") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/dataman/borealis_gaps/20230920_20231017_sas_rawacf_gaps.csv'
```

since the directory `/home/dataman/borealis_gaps/` did not exist. This script should check and create if necessary.

**Comment by tjk584** [comment]
Came here to make this exact issue. Just got me after waiting 1.5 hours to process 6 days of downtimes at clyde.
